module.exports = {
  AF_INET: 2,

  SCTP_FUTURE_ASSOC: 0,
  SCTP_CURRENT_ASSOC: 1,
  SCTP_ALL_ASSOC: 2,

  SCTP_BINDX_ADD_ADDR: 1,
  SCTP_BINDX_REM_ADDR: 2,

  SCTP_ASSOC_CHANGE: 0x8001,
  SCTP_PEER_ADDR_CHANGE: 0x8002,
  SCTP_SEND_FAILED: 0x8003,
  SCTP_REMOTE_ERROR: 0x8004,
  SCTP_SHUTDOWN_EVENT: 0x8005,
  SCTP_PARTIAL_DELIVERY_EVENT: 0x8006,
  SCTP_ADAPTATION_INDICATION: 0x8007,
  SCTP_AUTHENTICATION_EVENT: 0x8008,
  SCTP_SENDER_DRY_EVENT: 0x8009,
  SCTP_STREAM_RESET_EVENT: 0x800a,
  SCTP_ASSOC_RESET_EVENT: 0x800b,
  SCTP_STREAM_CHANGE_EVENT: 0x800c,
  SCTP_SEND_FAILED_EVENT: 0x800d,

  SCTP_COMM_UP: 0,
  SCTP_COMM_LOST: 1,
  SCTP_RESTART: 2,
  SCTP_SHUTDOWN_COMP: 3,
  SCTP_CANT_STR_ASSOC: 4,

  SCTP_AUTH_NEW_KEY: 0,
  SCTP_AUTH_FREE_KEY: 1,
  SCTP_AUTH_NO_AUTH: 2,

  SCTP_ADDR_AVAILABLE: 0,
  SCTP_ADDR_UNREACHABLE: 1,
  SCTP_ADDR_REMOVED: 2,
  SCTP_ADDR_ADDED: 3,
  SCTP_ADDR_MADE_PRIM: 4,
  SCTP_ADDR_CONFIRMED: 5,

  errno: {
    NO_ERROR: 0,
    EAGAIN: 11,
    ECONNRESET: 104,
    ENOTCONN: 107,
    ECONNREFUSED: 111,
    EINPROGRESS: 115,
    EPIPE: 32,
    EINVAL: 22,
    EADDRINUSE: 98,
    EADDRNOTAVAIL: 99,
  },

  MSG_EOR: 0x80,
  MSG_NOTIFICATION: 0x8000,

  SHUT_RDWR: 2,
};
