module.exports = {
  AF_INET: 2,

  SCTP_FUTURE_ASSOC: 0,
  SCTP_CURRENT_ASSOC: 1,
  SCTP_ALL_ASSOC: 2,

  SCTP_BINDX_ADD_ADDR: 1,
  SCTP_BINDX_REM_ADDR: 2,

  errno: {
    NO_ERROR: 0,
    EAGAIN: 11,
    ECONNRESET: 104,
    ENOTCONN: 107,
    ECONNREFUSED: 111,
    EINPROGRESS: 115,
    EPIPE: 32,
    EINVAL: 22,
    EADDRINUSE: 98,
    EADDRNOTAVAIL: 99,
  },

  MSG_EOR: 0x80,

  SHUT_RDWR: 2,
};
