name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Continous integration tests
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: npm
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsctp-dev valgrind
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Verify code with linter
        run: npm run lint
