name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, edited]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-title:
    uses: onomondo/shared-workflows/.github/workflows/verify-pr-title.yml@master
    secrets: inherit
    with:
      timeout: 5
