on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created || github.event_name == 'workflow_dispatch'  }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
        name: Checkout source code
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsctp-dev
      - run: npm ci
      - run: npm publish --access public
