on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created || github.event_name == 'workflow_dispatch'  }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ hashFiles('.node-version') == '' && '20.x' || '' }}
          node-version-file: ${{ hashFiles('.node-version') != '' && '.node-version' || '' }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install system dependencies
        run: sudo apt-get install -y libsctp-dev valgrind
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
