on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created || github.event_name == 'workflow_dispatch'  }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        name: Checkout source code
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsctp-dev
      - run: npm ci
      - run: npm publish --access public
